spring.application.name=timegrid-backend

# Pefil que esta sendo usado
spring.profiles.active=dev

timegrid.jwt.secret=${JWT_SECRET:change-this-secret-before-production-timegrid-jwt-secret}
timegrid.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
